// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.sberbank.jms.util.domain;

import ru.sberbank.jms.util.domain.JmsConfiguration;

privileged aspect JmsConfiguration_Roo_JavaBean {
    
    public String JmsConfiguration.getUrl() {
        return this.url;
    }
    
    public void JmsConfiguration.setUrl(String url) {
        this.url = url;
    }
    
}
