// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.sberbank.jms.util.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import ru.sberbank.jms.util.domain.JmsConfiguration;
import ru.sberbank.jms.util.domain.JmsConfigurationDataOnDemand;

privileged aspect JmsConfigurationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JmsConfigurationDataOnDemand: @Component;
    
    private Random JmsConfigurationDataOnDemand.rnd = new SecureRandom();
    
    private List<JmsConfiguration> JmsConfigurationDataOnDemand.data;
    
    public JmsConfiguration JmsConfigurationDataOnDemand.getNewTransientJmsConfiguration(int index) {
        JmsConfiguration obj = new JmsConfiguration();
        setDelay(obj, index);
        setQueueName(obj, index);
        setQueueNameReceive(obj, index);
        setUrl(obj, index);
        return obj;
    }
    
    public void JmsConfigurationDataOnDemand.setDelay(JmsConfiguration obj, int index) {
        int delay = index;
        if (delay < 5 || delay > 999999) {
            delay = 999999;
        }
        obj.setDelay(delay);
    }
    
    public void JmsConfigurationDataOnDemand.setQueueName(JmsConfiguration obj, int index) {
        String queueName = "queueName_" + index;
        obj.setQueueName(queueName);
    }
    
    public void JmsConfigurationDataOnDemand.setQueueNameReceive(JmsConfiguration obj, int index) {
        String queueNameReceive = "queueNameReceive_" + index;
        obj.setQueueNameReceive(queueNameReceive);
    }
    
    public void JmsConfigurationDataOnDemand.setUrl(JmsConfiguration obj, int index) {
        String url = "url_" + index;
        obj.setUrl(url);
    }
    
    public JmsConfiguration JmsConfigurationDataOnDemand.getSpecificJmsConfiguration(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JmsConfiguration obj = data.get(index);
        String id = obj.getConfigurationName();
        return JmsConfiguration.findJmsConfiguration(id);
    }
    
    public JmsConfiguration JmsConfigurationDataOnDemand.getRandomJmsConfiguration() {
        init();
        JmsConfiguration obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getConfigurationName();
        return JmsConfiguration.findJmsConfiguration(id);
    }
    
    public boolean JmsConfigurationDataOnDemand.modifyJmsConfiguration(JmsConfiguration obj) {
        return false;
    }
    
    public void JmsConfigurationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JmsConfiguration.findJmsConfigurationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JmsConfiguration' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JmsConfiguration>();
        for (int i = 0; i < 10; i++) {
            JmsConfiguration obj = getNewTransientJmsConfiguration(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
