// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.sberbank.jms.util.domain;

import org.springframework.beans.factory.annotation.Configurable;
import ru.sberbank.jms.util.domain.JmsConfigurationIntegrationTest;

privileged aspect JmsConfigurationIntegrationTest_Roo_Configurable {
    
    declare @type: JmsConfigurationIntegrationTest: @Configurable;
    
}
