// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.sberbank.jms.util.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import ru.sberbank.jms.util.domain.JmsMessage;
import ru.sberbank.jms.util.domain.JmsMessageDataOnDemand;

privileged aspect JmsMessageDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JmsMessageDataOnDemand: @Component;
    
    private Random JmsMessageDataOnDemand.rnd = new SecureRandom();
    
    private List<JmsMessage> JmsMessageDataOnDemand.data;
    
    public JmsMessage JmsMessageDataOnDemand.getNewTransientJmsMessage(int index) {
        JmsMessage obj = new JmsMessage();
        setMessageBody(obj, index);
        return obj;
    }
    
    public void JmsMessageDataOnDemand.setMessageBody(JmsMessage obj, int index) {
        String messageBody = "messageBody_" + index;
        obj.setMessageBody(messageBody);
    }
    
    public JmsMessage JmsMessageDataOnDemand.getSpecificJmsMessage(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JmsMessage obj = data.get(index);
        Long id = obj.getId();
        return JmsMessage.findJmsMessage(id);
    }
    
    public JmsMessage JmsMessageDataOnDemand.getRandomJmsMessage() {
        init();
        JmsMessage obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JmsMessage.findJmsMessage(id);
    }
    
    public boolean JmsMessageDataOnDemand.modifyJmsMessage(JmsMessage obj) {
        return false;
    }
    
    public void JmsMessageDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JmsMessage.findJmsMessageEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JmsMessage' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JmsMessage>();
        for (int i = 0; i < 10; i++) {
            JmsMessage obj = getNewTransientJmsMessage(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
