// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ru.sberbank.jms.util.domain;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import ru.sberbank.jms.util.domain.JmsMessage;
import ru.sberbank.jms.util.domain.JmsMessageDataOnDemand;
import ru.sberbank.jms.util.domain.JmsMessageIntegrationTest;

privileged aspect JmsMessageIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JmsMessageIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JmsMessageIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JmsMessageIntegrationTest: @Transactional;
    
    @Autowired
    JmsMessageDataOnDemand JmsMessageIntegrationTest.dod;
    
    @Test
    public void JmsMessageIntegrationTest.testCountJmsMessages() {
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", dod.getRandomJmsMessage());
        long count = JmsMessage.countJmsMessages();
        Assert.assertTrue("Counter for 'JmsMessage' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JmsMessageIntegrationTest.testFindJmsMessage() {
        JmsMessage obj = dod.getRandomJmsMessage();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to provide an identifier", id);
        obj = JmsMessage.findJmsMessage(id);
        Assert.assertNotNull("Find method for 'JmsMessage' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JmsMessage' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JmsMessageIntegrationTest.testFindAllJmsMessages() {
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", dod.getRandomJmsMessage());
        long count = JmsMessage.countJmsMessages();
        Assert.assertTrue("Too expensive to perform a find all test for 'JmsMessage', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JmsMessage> result = JmsMessage.findAllJmsMessages();
        Assert.assertNotNull("Find all method for 'JmsMessage' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JmsMessage' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JmsMessageIntegrationTest.testFindJmsMessageEntries() {
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", dod.getRandomJmsMessage());
        long count = JmsMessage.countJmsMessages();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JmsMessage> result = JmsMessage.findJmsMessageEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JmsMessage' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JmsMessage' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JmsMessageIntegrationTest.testFlush() {
        JmsMessage obj = dod.getRandomJmsMessage();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to provide an identifier", id);
        obj = JmsMessage.findJmsMessage(id);
        Assert.assertNotNull("Find method for 'JmsMessage' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJmsMessage(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JmsMessage' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JmsMessageIntegrationTest.testMergeUpdate() {
        JmsMessage obj = dod.getRandomJmsMessage();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to provide an identifier", id);
        obj = JmsMessage.findJmsMessage(id);
        boolean modified =  dod.modifyJmsMessage(obj);
        Integer currentVersion = obj.getVersion();
        JmsMessage merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JmsMessage' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JmsMessageIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", dod.getRandomJmsMessage());
        JmsMessage obj = dod.getNewTransientJmsMessage(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JmsMessage' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JmsMessage' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JmsMessageIntegrationTest.testRemove() {
        JmsMessage obj = dod.getRandomJmsMessage();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JmsMessage' failed to provide an identifier", id);
        obj = JmsMessage.findJmsMessage(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JmsMessage' with identifier '" + id + "'", JmsMessage.findJmsMessage(id));
    }
    
}
